### ISSUE TITLE
Pressing the Post It! button doesn't work

### ISSUE THREAD

**Issue by whippingdot** [headiscoding/Say-WHAT#3]
![image](https://user-images.githubusercontent.com/64354499/112620267-4a4bb180-8e4e-11eb-838c-45c1dc4294eb.png)

**Comment by mo-balsara** [comment]
Yeah I know we are trying to fix it. If you want to make a change make a pull request

**Comment by whippingdot** [comment]
ok ~~i ain't that smart BOI~~

**Comment by mo-balsara** [comment]
> ok ~i ain't that smart BOI~

It works now
